# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.0
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

licenses:
  - '.*'

script:
  - ./gradlew check lint --stacktrace --console=plain -PdisablePreDex

notifications:
  email: false
